/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_HOSTING_URL,
  generateRobotsTxt: true,
  sitemapSize: 7000,
  exclude: ['/404', '/server-sitemap.xml'],
  additionalPaths: async (config) => [
    await config.transform(config, '/ja'),
    await config.transform(config, '/ja/news'),
    await config.transform(config, '/ja/about'),
    await config.transform(config, '/ja/community'),
    await config.transform(config, '/ja/docs'),
    await config.transform(config, '/ja/support/rest'),
    await config.transform(config, '/en'),
    await config.transform(config, '/en/news'),
    await config.transform(config, '/en/about'),
    await config.transform(config, '/en/community'),
    await config.transform(config, '/en/docs'),
    await config.transform(config, '/en/support/rest'),
    await config.transform(config, '/ko'),
    await config.transform(config, '/ko/news'),
    await config.transform(config, '/ko/about'),
    await config.transform(config, '/ko/community'),
    await config.transform(config, '/ko/docs'),
    await config.transform(config, '/ko/support/rest'),
    await config.transform(config, '/zh'),
    await config.transform(config, '/zh/news'),
    await config.transform(config, '/zh/docs'),
    await config.transform(config, '/zh/about'),
    await config.transform(config, '/zh/community'),
    await config.transform(config, '/zh/support/rest'),
    await config.transform(config, '/zh-hant-tw'),
    await config.transform(config, '/zh-hant-tw/news'),
    await config.transform(config, '/zh-hant-tw/about'),
    await config.transform(config, '/zh-hant-tw/community'),
    await config.transform(config, '/zh-hant-tw/docs'),
    await config.transform(config, '/zh-hant-tw/support/rest'),
  ],
  robotsTxtOptions: {
    additionalSitemaps: [`${process.env.NEXT_PUBLIC_HOSTING_URL}/server-sitemap.xml`],
  },
};
