/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_HOSTING_URL,
  generateRobotsTxt: true,
  sitemapSize: 7000,
  exclude: ['/404', '/server-sitemap.xml'],
  additionalPaths: async (config) => [
    await config.transform(config, '/ja'),
    await config.transform(config, '/en'),
    await config.transform(config, '/ko'),
    await config.transform(config, '/zh'),
    await config.transform(config, '/zh-Hant-TW'),
    await config.transform(config, '/news/ja'),
    await config.transform(config, '/news/en'),
    await config.transform(config, '/news/ko'),
    await config.transform(config, '/news/zh'),
    await config.transform(config, '/news/zh-Hant-TW'),
    await config.transform(config, '/about/ja'),
    await config.transform(config, '/about/en'),
    await config.transform(config, '/about/ko'),
    await config.transform(config, '/about/zh'),
    await config.transform(config, '/about/zh-Hant-TW'),
    await config.transform(config, '/community/ja'),
    await config.transform(config, '/community/en'),
    await config.transform(config, '/community/ko'),
    await config.transform(config, '/community/zh'),
    await config.transform(config, '/community/zh-Hant-TW'),
    await config.transform(config, '/docs/ja'),
    await config.transform(config, '/docs/en'),
    await config.transform(config, '/docs/ko'),
    await config.transform(config, '/docs/zh'),
    await config.transform(config, '/docs/zh-Hant-TW'),
  ],
  robotsTxtOptions: {
    additionalSitemaps: [`${process.env.NEXT_PUBLIC_HOSTING_URL}/server-sitemap.xml`],
  },
};
